name: Label Issues

on:
  issues:
    types:
      - opened
      - reopened
      - edited
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  label_issue_and_pull_request:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Run label script
        run: node .github/scripts/label.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
