name: Label Issues

on:
  issues:
    types:
      - opened
      - reopened
      - edited

jobs:
  label_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues based on title
        uses: actions/github-script@v7
        with:
          script: |
            const issueTitle = context.payload.issue.title.toLowerCase();
            const issueNumber = context.payload.issue.number;
            const labels = [];

            const repoLables = await github.paginate(github.issues.listLabelsForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            for (const label of repoLables) {
              if (issueTitle.includes(label.name.toLowerCase())) {
                labels.push(label.name);
              }
            }

            if (labels.length > 0) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: labels
              });
            }
